[build]
  publish = ".next"
  command = "npm run build"

[context.production]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/about"
  to = "/about-me"
  status = 301